import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from 'next/link'
import Bsebhead from "../../components/bsebhead";
import styles from "../../styles/StatesPage.module.css";

const slug = () => {
  const router = useRouter();
  const { slug } = router.query;
  return (
    <>
      <Head>
        <title>{slug} | QuestionPaperz.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <Bsebhead />
        <h2>{slug} </h2>
        <p>Click to download</p>
        <div className={styles.year_tree}>
          {/* left side leafs */}
          <div className={styles.leaf_left}>
            <div className={styles.leaf}>
              <div className={styles.box}><Link href="#">Math</Link></div>
              <div className={styles.line}></div>
            </div>
            <div className={styles.leaf}>
              <div className={styles.box}><Link href="#">Science</Link></div>
              <div className={styles.line}></div>
            </div>
            <div className={styles.leaf}>
              <div className={styles.box}><Link href="#">Social Science</Link></div>
              <div className={styles.line}></div>
            </div>
            <div className={styles.leaf}>
              <div className={styles.box}><Link href="#">Sanskrit</Link></div>
              <div className={styles.line}></div>
            </div>
          </div>
          <div className={styles.tree_root}>
            <div className={styles.circle1}></div>
            <div className={styles.midline}></div>
            <div className={styles.circle2}></div>
          </div>
          <div className={styles.leaf_right}>
            <div className={styles.leaf}>
              <div className={styles.line}></div>
              <div className={styles.box}><Link href="#">Hindi</Link></div>
            </div>
            <div className={styles.leaf}>
              <div className={styles.line}></div>
              <div className={styles.box}><Link href="#">English</Link></div>
            </div>
            <div className={styles.leaf}>
              <div className={styles.line}></div>
              <div className={styles.box}><Link href="#">Urdu</Link></div>
            </div>
            <div className={styles.leaf}>
              <div className={styles.line}></div>
              <div className={styles.box}><Link href="#">Hindi</Link></div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default slug;
