import React from 'react'
import Link from 'next/link'
import Head from "next/head";
import Bsebhead from '../../components/bsebhead'
import styles from '../../styles/StatesPage.module.css'
const bseb = () => {
    return (
        <>
            <Head>
                <title>BSEB | QuestionPaperz.com</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <main className={styles.main}>
                <Bsebhead />


                {/* 10th class tree */}

                <div className={styles.tenth_class}>
                    <h3 className={styles.classname_h3}>10th Class</h3>
                    <div className={styles.year_tree}>
                        {/* left side leafs */}
                        <div className={styles.leaf_left}>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/10th class 2022">2022</Link></div>
                                <div className={styles.line}></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/10th class 2020">2020</Link></div>
                                <div className={styles.line}></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/10th class 2018">2018</Link></div>
                                <div className={styles.line}></div>
                            </div>
                        </div>
                        <div className={styles.tree_root}>
                            <div className={styles.circle1}></div>
                            <div className={styles.midline}></div>
                            <div className={styles.circle2}></div>
                        </div>
                        <div className={styles.leaf_right}>
                            <div className={styles.leaf}>
                                <div className={styles.line}></div>
                                <div className={styles.box}><Link href="/BSEB/10th class 2021">2021</Link></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.line}></div>
                                <div className={styles.box}><Link href="/BSEB/10th class 2019">2019</Link></div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr className={styles.hrt} />
                {/* 12th Science  */}

                <div className={styles.tenth_class}>
                    <h3 className={styles.classname_h3}>12th Science</h3>
                    <div className={styles.year_tree}>
                        {/* left side leafs */}
                        <div className={styles.leaf_left}>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Science 2022">2022</Link></div>
                                <div className={styles.line}></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Science 2020">2020</Link></div>
                                <div className={styles.line}></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Science 2018">2018</Link></div>
                                <div className={styles.line}></div>
                            </div>
                        </div>
                        <div className={styles.tree_root}>
                            <div className={styles.circle1}></div>
                            <div className={styles.midline}></div>
                            <div className={styles.circle2}></div>
                        </div>
                        <div className={styles.leaf_right}>
                            <div className={styles.leaf}>
                                <div className={styles.line}></div>
                                <div className={styles.box}><Link href="/BSEB/12th Science 2021">2021</Link></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.line}></div>
                                <div className={styles.box}><Link href="/BSEB/12th Science 2019">2019</Link></div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr className={styles.hrt} />
                {/* 12th Arts  */}

                <div className={styles.tenth_class}>
                    <h3 className={styles.classname_h3}>12th Arts</h3>
                    <div className={styles.year_tree}>
                        {/* left side leafs */}
                        <div className={styles.leaf_left}>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Arts 2022">2022</Link></div>
                                <div className={styles.line}></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Arts 2020">2020</Link></div>
                                <div className={styles.line}></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Arts 2018">2018</Link></div>
                                <div className={styles.line}></div>
                            </div>
                        </div>
                        <div className={styles.tree_root}>
                            <div className={styles.circle1}></div>
                            <div className={styles.midline}></div>
                            <div className={styles.circle2}></div>
                        </div>
                        <div className={styles.leaf_right}>
                            <div className={styles.leaf}>
                                <div className={styles.line}></div>
                                <div className={styles.box}><Link href="/BSEB/12th Arts 2021">2021</Link></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.line}></div>
                                <div className={styles.box}><Link href="/BSEB/12th Arts 2019">2019</Link></div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr className={styles.hrt} />
                {/* 12th Commerce  */}

                <div className={styles.tenth_class}>
                    <h3 className={styles.classname_h3}>12th Commerce</h3>
                    <div className={styles.year_tree}>
                        {/* left side leafs */}
                        <div className={styles.leaf_left}>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Commerce 2022">2022</Link></div>
                                <div className={styles.line}></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Commerce 2020">2020</Link></div>
                                <div className={styles.line}></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.box}><Link href="/BSEB/12th Commerce 2018">2018</Link></div>
                                <div className={styles.line}></div>
                            </div>
                        </div>
                        <div className={styles.tree_root}>
                            <div className={styles.circle1}></div>
                            <div className={styles.midline}></div>
                            <div className={styles.circle2}></div>
                        </div>
                        <div className={styles.leaf_right}>
                            <div className={styles.leaf}>
                                <div className={styles.line}></div>
                                <div className={styles.box}><Link href="/BSEB/12th Commerce 2021">2021</Link></div>
                            </div>
                            <div className={styles.leaf}>
                                <div className={styles.line}></div>
                                <div className={styles.box}><Link href="/BSEB/12th Commerce 2019">2019</Link></div>
                            </div>
                        </div>
                    </div>
                </div>

            </main>
        </>
    )
}

export default bseb