import React from 'react'
import { useRouter } from 'next/router'
import Head from "next/head";
import styles from '../../styles/StatesPage.module.css'

const slug = () => {
  const router = useRouter()
  const { slug } = router.query;
  return (
    <>
      <Head>
        <title>{slug} | QuestionPaperz.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      
      <main className={styles.main}>
        <img src="/BSEB-logo.png" alt="" />
        <h1>{slug}</h1>
        <hr />
      </main>
    </>
  );
}

export default slug