import React from "react";
import Head from "next/head";
import styles from '../styles/Home.module.css'
const entranceexam = () => {
  return (
    <>
      <Head>
        <title>Entrance Exams | QuestionPaperz.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.stateboard}>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/logo.svg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          </div>
          </main>
    </>
  );
};

export default entranceexam;
