import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QuestionPaperz.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <nav className={styles.mainnav}>
        <div className={styles.navlogo}>
          <img src="/logo.svg" alt="" />
          <h3>Questionpaperz.com</h3>
        </div>
        <ul>
          <Link href='/'><li><a>Home</a></li></Link>
          <Link href='/stateboards'><li><a>State Boards</a></li></Link>
          <Link href='/universities'><li><a>Universities</a></li></Link>
          <Link href='/entranceexam'><li><a>Entrance Exams</a></li></Link>
          <Link href='/notes'><li><a>Notes</a></li></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <div className={styles.intro_page}>
          <div className={styles.searchbar}>
            <input type="text" placeholder='Search Any Questions Papers....' />
            <div className={styles.side}>
              <img src="/searchicon.svg" alt="" className={styles.searchicon} />
            </div>
          </div>
          <div className={styles.introtext}>
            <div className={styles.headtext}>
              <h1>We Provide </h1>
              <p>State Board, University and Entrance Exam Previous Year Questions papers with Answers.</p>
            </div>
            <div className={styles.coverimg}>
              <img src="/coverimg2.svg" alt="" />
            </div>
          </div>
        </div>




      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/questionspaper.svg" alt="qp Logo" width={100} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
