import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QuestionPaperz.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/QP logo.png" />
      </Head>

      <nav className={styles.mainnav}>
        <div className={styles.navlogo}>
          <img src="/QP logo.png" alt="" />
          <h3>Questionpaperz.com</h3>
        </div>
        <ul>
          <li>Home</li>
          <li>State Boards</li>  
          <li>Universities</li>
          <li>Entrance Exams</li>
          <li>Notes</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <div className={styles.intro_page}>
          <div className={styles.searchbar}>
            <input type="text" placeholder='Search Any Questions Papers....' />
            <div className={styles.side}>
              <img src="/searchicon.svg" alt="" className={styles.searchicon} />
            </div>
          </div>
          <div className={styles.introtext}>

          </div>
        </div>

        

        
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/questionspaper.svg" alt="qp Logo" width={100} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
