import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home-QuestionPaperz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/QP logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to QuestionPaperz.com
        </h1>

        

        
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/questionspaper.svg" alt="Vercel Logo" width={100} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
