import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/state.module.css";
const stateboards = () => {
  return (
    <>
      <Head>
        <title>State Boards | QuestionPaperz.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.stateboard}>
          <Link href="/States/bsebhome">
            <div className={styles.sbs}>
              <div className={styles.sblogo}>
                <img src="/BSEB-logo.png" alt="" />
              </div>
              <div className={styles.sbname}>
                <h3>BSEB</h3>
              </div>
            </div>
          </Link>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="Jharkhand_Academic_Council.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>JAC</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="CBSE.jpg" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>CBSE</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="Andhra-State.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>APBE</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="BSEB-logo.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>BSEB</h3>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default stateboards;
