import React from "react";
import Head from "next/head";
import styles from '../styles/Home.module.css'
const universities = () => {
  return (
    <>
      <Head>
        <title>Universities | QuestionPaperz.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className={styles.main}>
        <div className={styles.stateboard}>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          <div className={styles.sbs}>
            <div className={styles.sblogo}>
              <img src="/velsuniv.png" alt="" />
            </div>
            <div className={styles.sbname}>
              <h3>Vels University</h3>
            </div>
          </div>
          </div>
          </main>
    </>
  );
};

export default universities;
